---
# This playbook lists all available variables that can be set for this role
# That includes defaults as well.
# For minimal needed variables, refer example playbooks in the examples/
# directory.

- name: Setting up backend
  remote_user: root
  hosts: servers
  gather_facts: false

  vars:
     # Firewall setup
     gluster_infra_fw_ports:
        - 2049/tcp
        - 54321/tcp
        - 5900/tcp
        - 5900-6923/tcp
        - 5666/tcp
        - 16514/tcp
     gluster_infra_fw_permanent: true
     gluster_infra_fw_state: enabled
     gluster_infra_fw_zone: public
     gluster_infra_fw_services:
        - glusterfs

     gluster_infra_vdo_state: present
     gluster_infra_vdo:
        - { name: 'hc_vdo', device: '/dev/vdb' }

     gluster_infra_vg_name: glusterfs_vg
     gluster_infra_pvs: /dev/vdb,/dev/vdc

     # Set a disk type - default: JBOD
     # Options: JBOD, RAID6, RAID10
     gluster_infra_disktype: RAID6

     # RAID6 and RAID10 diskcount
     gluster_infra_diskcount: 10

     # Stripe unit size always in KiB
     gluster_infra_stripe_unit_size: 128

     # Create a thick volume name
     gluster_infra_lv_thicklvname: glusterfs_thicklv
     gluster_infra_lv_thicklvsize: 20G

     gluster_infra_lv_thinpoolname: glusterfs_thinpool
     gluster_infra_lv_thicklvname: glusterfs_thicklv
     gluster_infra_lv_cachelvname: glusterfs_ssd_cache
     gluster_infra_lv_poolmetadatasize: 16G

     # Setup cache on the disks
     gluster_infra_ssd_disk: /dev/vdd
     gluster_infra_lv_cachelvsize: 20G

     # Create a thin volume
     gluster_infra_lv_logicalvols:
        - { lvname: 'glusterstore_thinlv', lvsize: '500G' }

     # Mount the devices
     gluster_infra_mount_devices:
        - { path: '/mnt/thinv',   lv: glusterstore_thinlv }
        - { path: '/mnt/thicklv', lv: "{{ gluster_infra_lv_thicklvname }}"}

  roles:
     - gluster.infra
